export default {
    box1_title: 'BEES ARE ESSENTIAL FOR PEOPLE AND ECOSYSTEMS',
    box1_text: 'We need honeybees – they pollinate our crops, provide food security and a diverse diet. For thousands of years, humans and honeybees have been in this symbiotic relationship, from which both sides profit enormously. Honeybees also play an important role in many ecosystems and the preservation of biodiversity around the globe. Unfortunately, they are increasingly threatened by climate change, invasive species, old and new pathogens and pesticides such as glyphosate. A condition we can no longer afford to ignore.',

    box2_title: 'MONITOR YOUR BEES WITH AI',
    box2_text: 'We are developing an AI-driven monitoring system for beehives. Easy-to-install microphones are placed inside the hive to sample your bee’s buzzing. The analysis of their sound frequencies tells us a lot: Are they going to swarm soon? Did they lose their queen? Are they stressed because of an infection or intruders? Our system will detect anomalies early on and provide you with information about what’s going on in your hives - based on the latest scientific discoveries.',

    box3_title: 'BEEKEEPING IS FACING NEW CHALLENGES',
    box3_text: 'We know that beekeeping can be hard: It is labor-intensive, time-consuming and requires in-depth knowledge - no matter if you are a professional or a hobbyist. Climate change imposes a new and unprecedented threat to beekeeping with heat waves, floods and other extreme weather conditions. In our warming climate, the invasive Asian hornet is quickly expanding north with protein-rich honeybees on their menu. We at HIVESOUND (and scientists) are deeply convinced that these new challenges for beekeeping can only be met by closely monitoring your bees at all times. To make your beekeeping life more comfortable, we support you with an all-encompassing digital platform for easy hive and business management and an AI-driven assistant.',
}