export default {
    box1_title: 'BIENEN SIND WICHTIG FÜR MENSCHEN UND ÖKOSYSTEME',
    box1_text: 'Wir brauchen Honigbienen - für die Bestäubung unserer Nutzpflanzen und die Sicherstellung einer abwechslungsreichen Ernährung. Seit über tausenden von Jahren sind Mensch und Honigbiene Teil dieser symbiontischen Beziehung, von denen beide Partner enorm profitieren. Honigbienen spielen darüber hinaus eine wichtige Rolle in vielen verschiedenen Ökosystemen und beim Erhalt der Biodiversität überall auf der Welt. Leider werden sie zunehmend bedroht: durch den Klimawandel, invasive Arten, alte und neue Krankheitserreger sowie Pestizide (z.B. Glyphosat). Wir können es uns nicht länger leisten, diesen Zustand zu ignorieren.',

    box2_title: 'ÜBERWACHE DEINE BIENEN MIT KI',
    box2_text: 'Wir entwickeln ein KI-gestütztes Überwachungssystem für Bienenstöcke. Mikrofone werden einfach im Inneren des Bienenstocks installiert und erfassen das Summen der Bienen. Die Analyse ihrer Schallfrequenzen sagt uns viel: Werden sie bald schwärmen? Haben sie ihre Königin verloren? Sind sie wegen einer Infektion oder Eindringlingen gestresst? Unser System erkennt Anomalien frühzeitig und liefert dir Informationen darüber, was in deinem Bienenstöcken vor sich geht. Dabei stützen wir uns auf neueste wissenschaftliche Erkenntnissen.',

    box3_title: 'DIE IMKEREI STEHT VOR NEUEN HERAUSFORDERUNGEN',
    box3_text: 'Wir wissen, dass die Imkerei anstrengend sein kann: Sie ist arbeitsintensiv, erfordert viel Zeit und fundiertes Wissen - egal, ob du Berufsimker:in oder Hobbyimker:in bist. Der Klimawandel bringt neue und beispiellose Bedrohungen für die Imkerei mit sich, z.B. Hitzewellen, flächendeckende Überschwemmungen und andere Extremwetterereignisse. Die Erwärmung trägt dazu bei, dass sich die invasive Asiatische Hornisse jetzt schnell nach Norden ausbreitet - und unsere proteinreichen Honigbienen stehen auf ihrem Speiseplan ganz oben. Wir von HIVESOUND sind genauso wie Wissenschaftler:innen davon überzeugt, dass die neuen Herausforderungen nur durch Echtzeit-Monitoring der Bienen bewältigt werden können. Wir unterstützen dich mit einer umfassenden digitalen Plattform und einem KI-gestützten Assistenten für eine einfache Verwaltung deiner Völker bzw. deiner Imkerei.',
}